### ISSUE TITLE
Nuxt3 - isolated-vm issue on Vercel

### ISSUE THREAD

**Issue by 20x-dz** [BuilderIO/builder#3605]
**Describe the bug**
Following the latest release ([sdk-vue@v2.0.17](https://github.com/BuilderIO/builder/releases/tag/%40builder.io%2Fsdk-vue%402.0.17)) with #3560, I immediately installed the latest version to see if #3288 was indeed fixed.

**To Reproduce**
1. Deploy to vercel through a github CI/CD pipeline (on `ubuntu-latest` with `node: 20` and nitro's [`vercel preset`](https://nitro.unjs.io/deploy/providers/vercel))
2. visit the preview url after deployment
3. See the following error in the logs:
```
Unhandled Rejection: Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /var/task/node_modules/isolated-vm/out/isolated_vm.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1586:18)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at /opt/rust/nodejs.js:1:11708
    at Function.dr (/opt/rust/nodejs.js:1:12082)
    at e.<computed>.oe._load (/opt/rust/nodejs.js:1:11678)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/var/task/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1469:14) {
  code: 'ERR_DLOPEN_FAILED'
}
Unhandled Rejection: Error: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /var/task/node_modules/isolated-vm/out/isolated_vm.node)
    at Module._extensions..node (node:internal/modules/cjs/loader:1586:18)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at /opt/rust/nodejs.js:1:11708
    at Function.dr (/opt/rust/nodejs.js:1:12082)
    at e.<computed>.oe._load (/opt/rust/nodejs.js:1:11678)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/var/task/node_modules/isolated-vm/isolated-vm.js:1:18)
    at Module._compile (node:internal/modules/cjs/loader:1469:14) {
  code: 'ERR_DLOPEN_FAILED'
}
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```

**Expected behavior**
See the rendered page.

**Screenshots**
![image](https://github.com/user-attachments/assets/ff7f21a6-5835-4a19-9f37-2c71f9c11cb1)

**Additional context**
Only the module was added to `nuxt.config.ts`:

```diff
diff --git a/frontend/nuxt.config.ts b/frontend/nuxt.config.ts
index 0f0bd96c..9db6641e 100644
--- a/frontend/nuxt.config.ts
+++ b/frontend/nuxt.config.ts
@@ -190,7 +190,13 @@ export default defineNuxtConfig({
     },
   },
   modules: [
-    "@builder.io/sdk-vue/nuxt",
+    [
+      "@builder.io/sdk-vue/nuxt",
+      {
+        includeCompiledCss: true, // Includes Builder.io CSS (default: true)
+        initializeNodeRuntime: true, // Initializes isolated VM in Node runtime (default: false)
+      },
+    ],
     "nuxt-svgo",
     "@nuxt/image",
     "@nuxtjs/tailwindcss",
 ```

Loosely related to #3604

**Comment by sidmohanty11** [comment]
Hello @20x-dz, thanks for the quick feedback. I was trying to reproduce this and I tweaked my `nuxt.config.ts` like this to use the vercel preset and it was able to build and deploy.
```ts
// https://nuxt.com/docs/api/configuration/nuxt-config
export default defineNuxtConfig({
  compatibilityDate: "2024-04-03",
  devtools: { enabled: true },
  nitro: {
    preset: "vercel",
  },
  modules: [
    [
      "@builder.io/sdk-vue/nuxt",
      {
        includeCompiledCss: true,
        initializeNodeRuntime: true,
      },
    ],
  ],
});
```
Repo:https://github.com/sidmohanty11/nuxt-isolated-vm2
hosted: https://nuxt-isolated-vm2.vercel.app/

Could you please check if I am missing any step to reproduce this bug?

**Comment by 20x-dz** [comment]
@sidmohanty11 Interesting. How do you build and deploy? We run the build on a github CI/CD pipeline (node20, ubuntu-latest) and deploy the output from there.

**Comment by sidmohanty11** [comment]
@20x-dz I just imported the project as a new project in Vercel. Could you please share an example workflow file that I can follow for the CI/CD pipeline?

**Comment by 20x-dz** [comment]
@sidmohanty11 https://gist.github.com/20x-dz/f55422a4bd652d293aa24ce79c4f3165 (I hope I didn't clean up too much, but that should do it). It's basically from the official documentation with some adjustments (tests, output, etc.): https://vercel.com/guides/how-can-i-use-github-actions-with-vercel

**Comment by sidmohanty11** [comment]
@20x-dz thank you so much! It was very helpful, I was able to reproduce this issue. We're actively searching for a solution for this; I'll keep you updated as soon as we find one.

**Comment by 20x-dz** [comment]
Great! 🤞 

I contacted Vercel support as well, although I think they might not have understood the problem. Anyway, here's their current statement, maybe it helps?

> The required dependency may have been missed by the build step, there is a mechanism by which these can be included manually which would be our recommended means to attempt to resolve this issue.
> 
> https://vercel.com/docs/projects/project-configuration#functions
>  
> First, create or modify your `vercel.json` file in the root of your project.
> Add the `functions` property to specify configurations for your functions.
> For each function that needs additional files, add an `includeFiles` property.
> An example entry can be seen below for reference on the structure.
> ```
> {
>   "functions": {
>     "api/myFunction.js": {
>       "includeFiles": ["data/**", "config/*.json"]
>     }
>   }
> }
> ```
> 
> This will ensure that the dependency is included which may resolve the issue that you are facing.

**Comment by sidmohanty11** [comment]
Hello @20x-dz, it appears that the `GLIBCXX` library is missing from the `ubuntu-latest` image used by Vercel. This library is required by the `isolated-vm` library to compile. As an interim solution, we suggest manually installing the `libstdc++6` library in your workflow YAML file which should fix this issue.

Repo: https://github.com/sidmohanty11/nuxt-isolated-vm2
YAML: https://github.com/sidmohanty11/nuxt-isolated-vm2/blob/main/.github/workflows/deploy.yml
Hosted: https://nuxt-isolated-vm2.vercel.app/

```yaml
name: Vercel Production Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches:
      - main
jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    # have to convert to container to install glibcxx
    container:
      image: node:20
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # install glibcxx as isolated vm depends on it
      - name: Install Dependencies for GLIBCXX
        run: |
          apt-get update && \
          apt-get install -y build-essential libstdc++6

      - name: Install Project Dependencies
        run: npm install

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
```

Meanwhile, we are working on adding better error handling and providing helpful warnings wherever possible for this issue.
